
import { Clinic, City, Treatment, Tier, BlogPost, ProductReview, ProductCategory, ClaimRequest, User, Review, NewsletterSubscriber } from './types';

export const INITIAL_USERS: User[] = [
    { uid: 'admin-001', name: 'Admin User', email: 'admin@transplantify.com', role: 'admin', favoriteClinics: [] },
    { uid: 'owner-001', name: 'Dr. Alan Farma', email: 'alan.farma@esteprime.com', role: 'clinic-owner', favoriteClinics: [] },
    { uid: 'user1', name: 'John D.', email: 'john.d@example.com', role: 'patient', favoriteClinics: [] },
    { uid: 'user2', name: 'Ahmed K.', email: 'ahmed.k@example.com', role: 'patient', favoriteClinics: [] },
    { uid: 'user3', name: 'James B.', email: 'james.b@example.com', role: 'patient', favoriteClinics: [] },
    { uid: 'user4', name: 'Chris P.', email: 'chris.p@example.com', role: 'patient', favoriteClinics: [] },
    { uid: 'user5', name: 'Maria G.', email: 'maria.g@example.com', role: 'patient', favoriteClinics: [] }
];

export const TREATMENTS: Treatment[] = [
    { id: 1, name: 'FUE (Follicular Unit Extraction)', description: 'A minimally invasive hair transplant method.' },
    { id: 2, name: 'DHI (Direct Hair Implantation)', description: 'A modified version of FUE for precise implantation.' },
    { id: 3, name: 'FUT (Follicular Unit Transplantation)', description: 'A traditional method involving a strip of scalp.' },
    { id: 4, name: 'PRP Therapy', description: 'Platelet-Rich Plasma therapy to stimulate hair growth.' },
];

export const CITIES: City[] = [
    { name: 'Istanbul', country: 'Turkey', imageUrl: 'https://picsum.photos/400/300?random=1' },
    { name: 'Dubai', country: 'UAE', imageUrl: 'https://picsum.photos/400/300?random=2' },
    { name: 'Delhi', country: 'India', imageUrl: 'https://picsum.photos/400/300?random=3' },
    { name: 'Mexico City', country: 'Mexico', imageUrl: 'https://picsum.photos/400/300?random=4' },
    { name: 'Tijuana', country: 'Mexico', imageUrl: 'https://picsum.photos/400/300?random=5' },
    { name: 'Bangkok', country: 'Thailand', imageUrl: 'https://picsum.photos/400/300?random=6' },
    { name: 'London', country: 'UK', imageUrl: 'https://picsum.photos/400/300?random=7' },
    { name: 'Los Angeles', country: 'USA', imageUrl: 'https://picsum.photos/400/300?random=8' },
    { name: 'Chicago', country: 'USA', imageUrl: 'https://picsum.photos/400/300?random=9' },
    { name: 'New York', country: 'USA', imageUrl: 'https://picsum.photos/400/300?random=10' },
    { name: 'Miami', country: 'USA', imageUrl: 'https://picsum.photos/400/300?random=11' },
    { name: 'Budapest', country: 'Hungary', imageUrl: 'https://picsum.photos/400/300?random=12' },
    { name: 'Warsaw', country: 'Poland', imageUrl: 'https://picsum.photos/400/300?random=13' },
    { name: 'Kuala Lumpur', country: 'Malaysia', imageUrl: 'https://picsum.photos/400/300?random=14' },
    { name: 'Seoul', country: 'South Korea', imageUrl: 'https://picsum.photos/400/300?random=15' }
];

export const CLINICS: Clinic[] = [
    // Istanbul
    {
        id: 1,
        name: 'EstePrime Clinic',
        tier: Tier.GOLD,
        ownerId: 'owner-001',
        city: 'Istanbul',
        country: 'Turkey',
        address: '123 Hair St, Sisli, Istanbul',
        latitude: 41.0602,
        longitude: 28.9868,
        rating: 4.9,
        reviewCount: 250,
        shortDescription: 'Leading FUE and DHI specialists in the heart of Istanbul. World-class results.',
        longDescription: 'EstePrime Clinic has been at the forefront of hair restoration for over a decade. Our state-of-the-art facility and experienced surgeons ensure you receive the best care possible. We specialize in natural-looking results with minimal downtime.',
        treatments: [1, 2, 4],
        contact: { phone: '+90 123 456 7890', website: 'esteprime.com' },
        reviews: [{ id: 1, userId: 'user1', clinicId: 1, rating: 5, comment: 'Life-changing experience. The staff was incredible.', date: '2023-10-15', status: 'approved' }],
        imageUrl: 'https://picsum.photos/800/600?random=1',
        galleryImages: ['https://picsum.photos/800/600?random=40', 'https://picsum.photos/800/600?random=41', 'https://picsum.photos/800/600?random=42'],
        videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
        verified: true,
        subscriptionStatus: 'active',
        stripeCustomerId: 'cus_123456789'
    },
    {
        id: 2,
        name: 'Turkey Hair Center',
        tier: Tier.PREMIUM,
        city: 'Istanbul',
        country: 'Turkey',
        address: '456 Bosphorus Ave, Beşiktaş, Istanbul',
        latitude: 41.0448,
        longitude: 29.0021,
        rating: 4.8,
        reviewCount: 180,
        shortDescription: 'Affordable, high-quality hair transplants with all-inclusive packages.',
        longDescription: 'We offer comprehensive packages for international patients, including hotel, transfers, and the procedure itself. Our focus is on providing a seamless and stress-free experience from start to finish.',
        treatments: [1, 2],
        contact: { phone: '+90 212 555 1234', website: 'turkeyhaircenter.com' },
        reviews: [],
        imageUrl: 'https://picsum.photos/800/600?random=16',
        galleryImages: ['https://picsum.photos/800/600?random=43', 'https://picsum.photos/800/600?random=44'],
        videoUrl: '',
        verified: false,
        aggregatedRating: 4.8,
        aggregatedReviewCount: 180,
        reviewSource: 'Google',
        reviewSourceUrl: '#',
    },
    // Dubai
    {
        id: 3,
        name: 'Dubai Hair Experts',
        tier: Tier.GOLD,
        city: 'Dubai',
        country: 'UAE',
        address: '789 Marina Walk, Dubai',
        latitude: 25.0784,
        longitude: 55.1389,
        rating: 4.9,
        reviewCount: 310,
        shortDescription: 'Luxury hair restoration with cutting-edge robotic FUE technology.',
        longDescription: 'Experience the future of hair transplantation in Dubai. Our clinic uses the latest robotic technology for unparalleled precision and density, all within a luxurious and private setting.',
        treatments: [1, 2],
        contact: { phone: '+971 4 555 9876', website: 'dubaihairexperts.ae' },
        reviews: [{ id: 2, userId: 'user2', clinicId: 3, rating: 5, comment: 'The best decision I ever made. Flawless results.', date: '2023-08-10', status: 'approved' }],
        imageUrl: 'https://picsum.photos/800/600?random=3',
        galleryImages: [],
        videoUrl: '',
        verified: true,
    },
    {
        id: 4,
        name: 'Emirates Scalp Clinic',
        tier: Tier.BASIC,
        city: 'Dubai',
        country: 'UAE',
        address: '101 Jumeirah Rd, Dubai',
        latitude: 25.2263,
        longitude: 55.2699,
        rating: 4.6,
        reviewCount: 90,
        shortDescription: 'Dedicated scalp and hair loss treatments for residents and visitors.',
        longDescription: 'Our team of dermatologists and surgeons provides a holistic approach to hair loss, offering both surgical and non-surgical solutions tailored to your individual needs.',
        treatments: [1, 4],
        contact: { phone: '+971 4 555 1122', website: 'emiratesscalp.ae' },
        reviews: [],
        imageUrl: 'https://picsum.photos/800/600?random=17',
        galleryImages: [],
        videoUrl: '',
        verified: false,
        aggregatedRating: 4.6,
        aggregatedReviewCount: 90,
        reviewSource: 'Google',
        reviewSourceUrl: '#',
    },
    // Delhi
    {
        id: 5,
        name: 'Delhi Hair Institute',
        tier: Tier.PREMIUM,
        city: 'Delhi',
        country: 'India',
        address: '22 G.K. Enclave, New Delhi',
        latitude: 28.5447,
        longitude: 77.2413,
        rating: 4.8,
        reviewCount: 220,
        shortDescription: 'India\'s leading destination for advanced FUE and FUT procedures.',
        longDescription: 'With a team of award-winning surgeons, Delhi Hair Institute is a center of excellence in hair restoration, known for handling complex cases with outstanding results.',
        treatments: [1, 3, 4],
        contact: { phone: '+91 11 4567 8901', website: 'delhihairinstitute.in' },
        reviews: [],
        imageUrl: 'https://picsum.photos/800/600?random=18',
        galleryImages: [],
        videoUrl: '',
        verified: true,
        aggregatedRating: 4.8,
        aggregatedReviewCount: 220,
        reviewSource: 'Google',
        reviewSourceUrl: '#',
    },
    {
        id: 6,
        name: 'Capital Hair Restoration',
        tier: Tier.BASIC,
        city: 'Delhi',
        country: 'India',
        address: '55 Karol Bagh, New Delhi',
        latitude: 28.6518,
        longitude: 77.1910,
        rating: 4.7,
        reviewCount: 150,
        shortDescription: 'Cost-effective and reliable hair transplant services in the capital.',
        longDescription: 'We believe everyone deserves to feel confident. Our clinic provides high-quality hair transplants at accessible prices, without compromising on safety or results.',
        treatments: [1, 3],
        contact: { phone: '+91 11 2345 6789', website: 'capitalhair.in' },
        reviews: [],
        imageUrl: 'https://picsum.photos/800/600?random=19',
        galleryImages: [],
        videoUrl: '',
        verified: false,
        aggregatedRating: 4.7,
        aggregatedReviewCount: 150,
        reviewSource: 'Google',
        reviewSourceUrl: '#',
    },
    // Mexico City
    {
        id: 7,
        name: 'CDMX Hair Clinic',
        tier: Tier.GOLD,
        city: 'Mexico City',
        country: 'Mexico',
        address: 'Paseo de la Reforma 500, CDMX',
        latitude: 19.4270,
        longitude: -99.1712,
        rating: 4.9,
        reviewCount: 280,
        shortDescription: 'Premier hair transplant clinic in Mexico City with US-trained surgeons.',
        longDescription: 'CDMX Hair Clinic sets the standard for hair restoration in Latin America. Our bilingual team and state-of-the-art facility attract patients from all over the world.',
        treatments: [1, 2, 4],
        contact: { phone: '+52 55 1234 5678', website: 'cdmxhair.com' },
        reviews: [],
        imageUrl: 'https://picsum.photos/800/600?random=20',
        galleryImages: [],
        videoUrl: '',
        verified: true,
        aggregatedRating: 4.9,
        aggregatedReviewCount: 280,
        reviewSource: 'Google',
        reviewSourceUrl: '#',
    },
    {
        id: 8,
        name: 'Hair Mexico Polanco',
        tier: Tier.PREMIUM,
        city: 'Mexico City',
        country: 'Mexico',
        address: 'Av. Presidente Masaryk 111, Polanco',
        latitude: 19.4326,
        longitude: -99.1843,
        rating: 4.8,
        reviewCount: 190,
        shortDescription: 'Boutique clinic in the heart of Polanco specializing in DHI.',
        longDescription: 'Our clinic offers a personalized and discreet experience, focusing on the DHI method for maximum density and natural-looking results. We cater to a discerning clientele seeking the best.',
        treatments: [2, 4],
        contact: { phone: '+52 55 8765 4321', website: 'hairmexicopolanco.com' },
        reviews: [],
        imageUrl: 'https://picsum.photos/800/600?random=21',
        galleryImages: [],
        videoUrl: '',
        verified: false,
        aggregatedRating: 4.8,
        aggregatedReviewCount: 190,
        reviewSource: 'Google',
        reviewSourceUrl: '#',
    },
    // Tijuana
    {
        id: 9,
        name: 'Tijuana Hair Pros',
        tier: Tier.PREMIUM,
        city: 'Tijuana',
        country: 'Mexico',
        address: 'Av. Revolución 1988, Tijuana',
        latitude: 32.5284,
        longitude: -117.0312,
        rating: 4.8,
        reviewCount: 215,
        shortDescription: 'Top-quality, affordable hair transplants just south of the border.',
        longDescription: 'Tijuana Hair Pros offers American-standard medical care at a fraction of the cost. Our board-certified surgeons and modern clinic make us a top choice for medical tourists from the US and Canada.',
        treatments: [1, 2],
        contact: { phone: '+52 664 123 4567', website: 'tjhairpros.com' },
        reviews: [],
        imageUrl: 'https://picsum.photos/800/600?random=6',
        galleryImages: [],
        videoUrl: '',
        verified: true,
        aggregatedRating: 4.8,
        aggregatedReviewCount: 215,
        reviewSource: 'Google',
        reviewSourceUrl: '#',
    },
    {
        id: 10,
        name: 'Baja Hair Center',
        tier: Tier.BASIC,
        city: 'Tijuana',
        country: 'Mexico',
        address: 'Blvd. Agua Caliente 1053, Tijuana',
        latitude: 32.5186,
        longitude: -117.0132,
        rating: 4.7,
        reviewCount: 170,
        shortDescription: 'Experienced and trusted clinic for medical tourists.',
        longDescription: 'With over 15 years of experience, Baja Hair Center is a trusted name in hair restoration. We provide safe, effective, and affordable procedures for patients seeking value and quality.',
        treatments: [1, 3],
        contact: { phone: '+52 664 987 6543', website: 'bajahair.com' },
        reviews: [],
        imageUrl: 'https://picsum.photos/800/600?random=22',
        galleryImages: [],
        videoUrl: '',
        verified: false,
        aggregatedRating: 4.7,
        aggregatedReviewCount: 170,
        reviewSource: 'Google',
        reviewSourceUrl: '#',
    },
    // Bangkok
    {
        id: 11,
        name: 'Bangkok Beauty Hair',
        tier: Tier.PREMIUM,
        city: 'Bangkok',
        country: 'Thailand',
        address: '101 Sukhumvit Rd, Bangkok',
        latitude: 13.7388,
        longitude: 100.5815,
        rating: 4.7,
        reviewCount: 155,
        shortDescription: 'Affordable excellence in hair transplantation in vibrant Bangkok.',
        longDescription: 'Combining Thai hospitality with international medical standards, Bangkok Beauty Hair offers high-quality hair transplants at a competitive price. Our experienced team is fluent in English and ready to guide you through your journey.',
        treatments: [1, 2, 4],
        contact: { phone: '+66 2 123 4567', website: 'bkkbeautyhair.com' },
        reviews: [],
        imageUrl: 'https://picsum.photos/800/600?random=4',
        galleryImages: [],
        videoUrl: '',
        verified: false,
        aggregatedRating: 4.7,
        aggregatedReviewCount: 155,
        reviewSource: 'Google',
        reviewSourceUrl: '#',
    },
    {
        id: 12,
        name: 'Siam Hair Institute',
        tier: Tier.GOLD,
        city: 'Bangkok',
        country: 'Thailand',
        address: 'Siam Paragon, 5th Floor, Bangkok',
        latitude: 13.7465,
        longitude: 100.5348,
        rating: 4.9,
        reviewCount: 290,
        shortDescription: 'World-renowned hair transplant artistry in a world-class location.',
        longDescription: 'Led by the acclaimed Dr. Somsak, Siam Hair Institute is where artistry meets science. We are known for creating incredibly natural hairlines and achieving high-density results.',
        treatments: [1, 2],
        contact: { phone: '+66 2 987 6543', website: 'siamhair.th' },
        reviews: [],
        imageUrl: 'https://picsum.photos/800/600?random=23',
        galleryImages: [],
        videoUrl: '',
        verified: true,
        aggregatedRating: 4.9,
        aggregatedReviewCount: 290,
        reviewSource: 'Google',
        reviewSourceUrl: '#',
    },
    // London
    {
        id: 13,
        name: 'London Scalp Clinic',
        tier: Tier.PREMIUM,
        city: 'London',
        country: 'UK',
        address: '10 Harley St, London',
        latitude: 51.5171,
        longitude: -0.1464,
        rating: 4.6,
        reviewCount: 95,
        shortDescription: 'Harley Street quality hair restoration and scalp micropigmentation.',
        longDescription: 'Located in the heart of London\'s medical district, our clinic provides comprehensive solutions for hair loss, from surgical transplantation to non-invasive treatments like SMP and PRP therapy.',
        treatments: [1, 3, 4],
        contact: { phone: '+44 20 7123 4567', website: 'londonscalp.co.uk' },
        reviews: [{ id: 3, userId: 'user3', clinicId: 13, rating: 4, comment: 'Good results, but the waiting list was quite long.', date: '2023-05-19', status: 'approved' }],
        imageUrl: 'https://picsum.photos/800/600?random=5',
        galleryImages: [],
        videoUrl: '',
        verified: false,
    },
    {
        id: 14,
        name: 'The Kensington Hair Clinic',
        tier: Tier.GOLD,
        city: 'London',
        country: 'UK',
        address: '12 Kensington High St, London',
        latitude: 51.5015,
        longitude: -0.1915,
        rating: 5.0,
        reviewCount: 120,
        shortDescription: 'Exclusive clinic offering bespoke hair restoration for a discerning clientele.',
        longDescription: 'The Kensington Hair Clinic provides a truly bespoke service. Every patient is treated by our lead surgeon, ensuring the highest standards of care and attention to detail from start to finish.',
        treatments: [1, 2, 4],
        contact: { phone: '+44 20 8888 9999', website: 'kenhair.co.uk' },
        reviews: [],
        imageUrl: 'https://picsum.photos/800/600?random=24',
        galleryImages: [],
        videoUrl: '',
        verified: true,
        aggregatedRating: 5.0,
        aggregatedReviewCount: 120,
        reviewSource: 'Google',
        reviewSourceUrl: '#',
    },
    // Los Angeles
    {
        id: 15,
        name: 'LA Hair Institute',
        tier: Tier.GOLD,
        city: 'Los Angeles',
        country: 'USA',
        address: '456 Follicle Ave, Beverly Hills',
        latitude: 34.0736,
        longitude: -118.4004,
        rating: 4.8,
        reviewCount: 180,
        shortDescription: 'Celebrity-trusted clinic in Los Angeles offering advanced hair solutions.',
        longDescription: 'At LA Hair Institute, we combine artistry with science to create undetectable hair transplants. Our team is dedicated to providing personalized treatment plans to meet your specific goals.',
        treatments: [1, 3, 4],
        contact: { phone: '+1 310 555 0123', website: 'lahair.com' },
        reviews: [{ id: 4, userId: 'user4', clinicId: 15, rating: 5, comment: 'Felt like a VIP. The results are amazing.', date: '2023-11-01', status: 'approved' }],
        imageUrl: 'https://picsum.photos/800/600?random=2',
        galleryImages: [],
        videoUrl: '',
        verified: true,
    },
    {
        id: 16,
        name: 'SoCal Hair Restoration',
        tier: Tier.PREMIUM,
        city: 'Los Angeles',
        country: 'USA',
        address: '789 Sunset Blvd, Los Angeles',
        latitude: 34.0983,
        longitude: -118.3258,
        rating: 4.7,
        reviewCount: 130,
        shortDescription: 'Cutting-edge FUE and PRP therapy with a focus on natural results.',
        longDescription: 'SoCal Hair Restoration is dedicated to the latest techniques in hair restoration. We pride ourselves on creating soft, natural hairlines that are indistinguishable from the real thing.',
        treatments: [1, 4],
        contact: { phone: '+1 323 555 4567', website: 'socalhair.com' },
        reviews: [],
        imageUrl: 'https://picsum.photos/800/600?random=25',
        galleryImages: [],
        videoUrl: '',
        verified: false,
        aggregatedRating: 4.7,
        aggregatedReviewCount: 130,
        reviewSource: 'Google',
        reviewSourceUrl: '#',
    },
    // Chicago
    {
        id: 17,
        name: 'Chicago Hair Masters',
        tier: Tier.GOLD,
        city: 'Chicago',
        country: 'USA',
        address: '1 Magnificent Mile, Chicago, IL',
        latitude: 41.8924,
        longitude: -87.6236,
        rating: 4.9,
        reviewCount: 200,
        shortDescription: 'Leading hair transplant surgeons in the Midwest.',
        longDescription: 'Our clinic on the Magnificent Mile is renowned for its exceptional patient care and consistently outstanding results. We utilize both FUE and FUT to best suit our patients\' needs.',
        treatments: [1, 3, 4],
        contact: { phone: '+1 312 555 1111', website: 'chicagohairmasters.com' },
        reviews: [],
        imageUrl: 'https://picsum.photos/800/600?random=26',
        galleryImages: [],
        videoUrl: '',
        verified: true,
        aggregatedRating: 4.9,
        aggregatedReviewCount: 200,
        reviewSource: 'Google',
        reviewSourceUrl: '#',
    },
    {
        id: 18,
        name: 'Windy City Hair Solutions',
        tier: Tier.BASIC,
        city: 'Chicago',
        country: 'USA',
        address: '22 Lincoln Ave, Chicago, IL',
        latitude: 41.9184,
        longitude: -87.6394,
        rating: 4.6,
        reviewCount: 85,
        shortDescription: 'Comprehensive hair loss solutions for men and women.',
        longDescription: 'We offer a range of services from medical management of hair loss to surgical restoration, providing a complete care path for our patients.',
        treatments: [1, 4],
        contact: { phone: '+1 773 555 2222', website: 'windycityhair.com' },
        reviews: [],
        imageUrl: 'https://picsum.photos/800/600?random=27',
        galleryImages: [],
        videoUrl: '',
        verified: false,
        aggregatedRating: 4.6,
        aggregatedReviewCount: 85,
        reviewSource: 'Google',
        reviewSourceUrl: '#',
    },
    // New York
    {
        id: 19,
        name: 'NYC Hair Group',
        tier: Tier.GOLD,
        city: 'New York',
        country: 'USA',
        address: '5th Avenue, New York, NY',
        latitude: 40.7742,
        longitude: -73.9655,
        rating: 5.0,
        reviewCount: 350,
        shortDescription: 'The pinnacle of hair restoration artistry in Manhattan.',
        longDescription: 'Our team of Ivy League-educated surgeons are artists as well as doctors. We specialize in high-density FUE procedures for the most demanding clients.',
        treatments: [1, 2, 4],
        contact: { phone: '+1 212 555 3000', website: 'nychairgroup.com' },
        reviews: [],
        imageUrl: 'https://picsum.photos/800/600?random=28',
        galleryImages: [],
        videoUrl: '',
        verified: true,
        aggregatedRating: 5.0,
        aggregatedReviewCount: 350,
        reviewSource: 'Google',
        reviewSourceUrl: '#',
    },
    {
        id: 20,
        name: 'Gotham Hair Institute',
        tier: Tier.PREMIUM,
        city: 'New York',
        country: 'USA',
        address: '1 Wall Street, New York, NY',
        latitude: 40.7075,
        longitude: -74.0113,
        rating: 4.8,
        reviewCount: 210,
        shortDescription: 'Advanced robotic FUE and DHI services in the financial district.',
        longDescription: 'We cater to busy professionals who demand efficiency and excellence. Our robotic technology ensures precise, consistent results with minimal downtime.',
        treatments: [1, 2],
        contact: { phone: '+1 212 555 4000', website: 'gothamhair.com' },
        reviews: [],
        imageUrl: 'https://picsum.photos/800/600?random=29',
        galleryImages: [],
        videoUrl: '',
        verified: false,
        aggregatedRating: 4.8,
        aggregatedReviewCount: 210,
        reviewSource: 'Google',
        reviewSourceUrl: '#',
    },
    // Miami
    {
        id: 21,
        name: 'Miami Hair & Vein',
        tier: Tier.PREMIUM,
        city: 'Miami',
        country: 'USA',
        address: '1 Ocean Drive, South Beach, FL',
        latitude: 25.7698,
        longitude: -80.1328,
        rating: 4.7,
        reviewCount: 160,
        shortDescription: 'Get the perfect hairline to match the Miami lifestyle.',
        longDescription: 'Our clinic specializes in creating natural, youthful hairlines suitable for an active, outdoor lifestyle. We use advanced FUE techniques to ensure results look great from every angle.',
        treatments: [1, 4],
        contact: { phone: '+1 305 555 5000', website: 'miamihair.com' },
        reviews: [],
        imageUrl: 'https://picsum.photos/800/600?random=30',
        galleryImages: [],
        videoUrl: '',
        verified: true,
        aggregatedRating: 4.7,
        aggregatedReviewCount: 160,
        reviewSource: 'Google',
        reviewSourceUrl: '#',
    },
    {
        id: 22,
        name: 'Florida Hair Solutions',
        tier: Tier.BASIC,
        city: 'Miami',
        country: 'USA',
        address: 'Biscayne Blvd, Miami, FL',
        latitude: 25.7907,
        longitude: -80.1918,
        rating: 4.6,
        reviewCount: 110,
        shortDescription: 'Affordable and effective hair restoration in South Florida.',
        longDescription: 'Providing a range of hair loss solutions to the diverse community of Miami, we are committed to delivering excellent results and patient care.',
        treatments: [1, 3],
        contact: { phone: '+1 305 555 6000', website: 'flhairsolutions.com' },
        reviews: [],
        imageUrl: 'https://picsum.photos/800/600?random=31',
        galleryImages: [],
        videoUrl: '',
        verified: false,
        aggregatedRating: 4.6,
        aggregatedReviewCount: 110,
        reviewSource: 'Google',
        reviewSourceUrl: '#',
    },
    // Budapest
    {
        id: 23,
        name: 'Budapest Hair Clinic',
        tier: Tier.GOLD,
        city: 'Budapest',
        country: 'Hungary',
        address: 'Andrássy út 10, Budapest',
        latitude: 47.5009,
        longitude: 19.0532,
        rating: 4.9,
        reviewCount: 240,
        shortDescription: 'Europe\'s top destination for affordable, high-quality hair transplants.',
        longDescription: 'We combine Hungarian medical excellence with affordable pricing, making us a top choice for patients from the UK, Germany, and beyond. Our packages are all-inclusive.',
        treatments: [1, 2],
        contact: { phone: '+36 1 234 5678', website: 'budapesthairclinic.hu' },
        reviews: [],
        imageUrl: 'https://picsum.photos/800/600?random=32',
        galleryImages: [],
        videoUrl: '',
        verified: true,
        aggregatedRating: 4.9,
        aggregatedReviewCount: 240,
        reviewSource: 'Google',
        reviewSourceUrl: '#',
    },
    {
        id: 24,
        name: 'Hair Palace Hungary',
        tier: Tier.PREMIUM,
        city: 'Budapest',
        country: 'Hungary',
        address: 'Váci utca 20, Budapest',
        latitude: 47.4957,
        longitude: 19.0520,
        rating: 4.8,
        reviewCount: 190,
        shortDescription: 'Guaranteed results and lifetime support in beautiful Budapest.',
        longDescription: 'We are so confident in our results that we offer a written guarantee on every procedure. Our commitment to patient satisfaction is our number one priority.',
        treatments: [1, 2, 4],
        contact: { phone: '+36 1 876 5432', website: 'hairpalace.hu' },
        reviews: [],
        imageUrl: 'https://picsum.photos/800/600?random=33',
        galleryImages: [],
        videoUrl: '',
        verified: false,
        aggregatedRating: 4.8,
        aggregatedReviewCount: 190,
        reviewSource: 'Google',
        reviewSourceUrl: '#',
    },
    // Warsaw
    {
        id: 25,
        name: 'Warsaw Hair Experts',
        tier: Tier.PREMIUM,
        city: 'Warsaw',
        country: 'Poland',
        address: 'ul. Nowy Świat 50, Warsaw',
        latitude: 52.2319,
        longitude: 21.0154,
        rating: 4.7,
        reviewCount: 150,
        shortDescription: 'Modern hair restoration techniques in the heart of Poland.',
        longDescription: 'Our clinic in Warsaw uses the latest FUE and DHI technologies, providing results that meet the highest European standards at a competitive price point.',
        treatments: [1, 2],
        contact: { phone: '+48 22 123 4567', website: 'warsawhairexperts.pl' },
        reviews: [],
        imageUrl: 'https://picsum.photos/800/600?random=34',
        galleryImages: [],
        videoUrl: '',
        verified: true,
        aggregatedRating: 4.7,
        aggregatedReviewCount: 150,
        reviewSource: 'Google',
        reviewSourceUrl: '#',
    },
    {
        id: 26,
        name: 'Poland Hair Clinic',
        tier: Tier.BASIC,
        city: 'Warsaw',
        country: 'Poland',
        address: 'Al. Jerozolimskie 100, Warsaw',
        latitude: 52.2272,
        longitude: 20.9926,
        rating: 4.6,
        reviewCount: 90,
        shortDescription: 'Safe and affordable hair transplants with experienced doctors.',
        longDescription: 'A popular choice for medical tourists, we offer transparent pricing and a friendly, English-speaking staff to guide you through your hair restoration journey.',
        treatments: [1, 3],
        contact: { phone: '+48 22 765 4321', website: 'polhair.pl' },
        reviews: [],
        imageUrl: 'https://picsum.photos/800/600?random=35',
        galleryImages: [],
        videoUrl: '',
        verified: false,
        aggregatedRating: 4.6,
        aggregatedReviewCount: 90,
        reviewSource: 'Google',
        reviewSourceUrl: '#',
    },
    // Kuala Lumpur
    {
        id: 27,
        name: 'KL Hair Solutions',
        tier: Tier.GOLD,
        city: 'Kuala Lumpur',
        country: 'Malaysia',
        address: 'Petronas Towers, Kuala Lumpur',
        latitude: 3.1578,
        longitude: 101.7119,
        rating: 4.9,
        reviewCount: 220,
        shortDescription: 'Leading-edge hair transplant technology in Southeast Asia.',
        longDescription: 'Located in the iconic Petronas Towers, our clinic offers world-class facilities and is a leader in robotic FUE technology in the ASEAN region.',
        treatments: [1, 2, 4],
        contact: { phone: '+60 3 1234 5678', website: 'klhair.my' },
        reviews: [],
        imageUrl: 'https://picsum.photos/800/600?random=36',
        galleryImages: [],
        videoUrl: '',
        verified: true,
        aggregatedRating: 4.9,
        aggregatedReviewCount: 220,
        reviewSource: 'Google',
        reviewSourceUrl: '#',
    },
    {
        id: 28,
        name: 'Malaysia Hair Institute',
        tier: Tier.PREMIUM,
        city: 'Kuala Lumpur',
        country: 'Malaysia',
        address: 'Jalan Bukit Bintang, Kuala Lumpur',
        latitude: 3.1466,
        longitude: 101.7101,
        rating: 4.8,
        reviewCount: 170,
        shortDescription: 'Expert care and natural results in Malaysia\'s vibrant capital.',
        longDescription: 'Our experienced team of surgeons and technicians are dedicated to the art and science of hair restoration, serving both local and international patients.',
        treatments: [1, 2],
        contact: { phone: '+60 3 8765 4321', website: 'myhairinstitute.com' },
        reviews: [],
        imageUrl: 'https://picsum.photos/800/600?random=37',
        galleryImages: [],
        videoUrl: '',
        verified: false,
        aggregatedRating: 4.8,
        aggregatedReviewCount: 170,
        reviewSource: 'Google',
        reviewSourceUrl: '#',
    },
    // Seoul
    {
        id: 29,
        name: 'Seoul Beauty Hair',
        tier: Tier.GOLD,
        city: 'Seoul',
        country: 'South Korea',
        address: 'Gangnam-gu, Seoul',
        latitude: 37.5172,
        longitude: 127.0473,
        rating: 5.0,
        reviewCount: 400,
        shortDescription: 'The gold standard in Korean hair transplant technology and aesthetics.',
        longDescription: 'In a city known for its exacting beauty standards, our clinic is the top choice. We specialize in high-density, ultra-natural FUE for a flawless, undetectable result.',
        treatments: [1, 2],
        contact: { phone: '+82 2 1234 5678', website: 'seoulbeautyhair.kr' },
        reviews: [],
        imageUrl: 'https://picsum.photos/800/600?random=38',
        galleryImages: [],
        videoUrl: '',
        verified: true,
        aggregatedRating: 5.0,
        aggregatedReviewCount: 400,
        reviewSource: 'Google',
        reviewSourceUrl: '#',
    },
    {
        id: 30,
        name: 'K-Hair Transplant Center',
        tier: Tier.PREMIUM,
        city: 'Seoul',
        country: 'South Korea',
        address: 'Myeongdong, Seoul',
        latitude: 37.5634,
        longitude: 126.9827,
        rating: 4.8,
        reviewCount: 250,
        shortDescription: 'Advanced techniques for both male and female hair loss.',
        longDescription: 'We offer specialized procedures including eyebrow and eyelash transplants, alongside our renowned scalp hair restoration services, using the latest Korean technology.',
        treatments: [1, 2, 4],
        contact: { phone: '+82 2 8765 4321', website: 'khair.kr' },
        reviews: [],
        imageUrl: 'https://picsum.photos/800/600?random=39',
        galleryImages: [],
        videoUrl: '',
        verified: false,
        aggregatedRating: 4.8,
        aggregatedReviewCount: 250,
        reviewSource: 'Google',
        reviewSourceUrl: '#',
    }
];

export const PRICING_TIERS = [
    {
        name: 'Basic',
        price: '$0',
        description: 'The essential first step to establish your online presence and manage your reputation.',
        features: [
            'Claim & Verify Listing',
            'Appear in Standard Search',
            'Respond to Reviews',
            '1 Photo Upload'
        ],
        cta: 'Get Listed Free',
        color: 'gray'
    },
    {
        name: 'Premium Partner',
        price: '$49',
        per: '/mo',
        description: 'Stand out from the competition, build trust, and generate direct leads.',
        features: [
            'Everything in Basic, plus:',
            'Enhanced Search Placement',
            '5 Photo Gallery',
            '"Request a Quote" Button',
            'Premium Partner Badge'
        ],
        cta: 'Go Premium',
        color: 'blue'
    },
    {
        name: 'Gold Partner',
        price: '$99',
        per: '/mo',
        description: 'Dominate your market with maximum visibility and powerful business tools.',
        features: [
            'Everything in Premium, plus:',
            'Guaranteed "Featured" Placement',
            'Highlighted Search Listing',
            'Unlimited Photos & 1 Video Upload',
            'Profile Analytics Dashboard',
            'AI Review & Content Tools',
        ],
        cta: 'Go Gold',
        color: 'amber'
    }
];

export const CUSTOM_SERVICE = {
    title: 'Enterprise Solution: AI Chatbot Receptionist',
    description: 'Automate your patient inquiries and booking process with a custom-trained AI receptionist. Our chatbot integrates with your website to answer common questions, qualify leads, and schedule consultations 24/7, freeing up your staff to focus on patient care.',
    cta: 'Contact Us for a Quote'
};


export const BLOG_POSTS: BlogPost[] = [
    {
        id: 1,
        title: 'The Ultimate Guide to FUE Hair Transplants in 2024',
        author: 'Dr. Jane Smith',
        date: '2024-07-15',
        summary: 'Thinking about an FUE procedure? This comprehensive guide covers everything you need to know, from the initial consultation to the final results. Learn about the technology, recovery process, and what to expect.',
        content: `FUE, or Follicular Unit Extraction, has revolutionized the field of hair restoration. Unlike the traditional FUT (strip) method, FUE involves extracting individual hair follicles from a donor area (typically the back of the head) and implanting them into thinning or bald areas.\n\n**Key Advantages of FUE:**\n- Minimally invasive with no linear scar.\n- Faster recovery time compared to FUT.\n- Ideal for patients who prefer shorter hairstyles.\n\n**The Procedure:**\nThe process begins with a consultation to assess your hair loss and determine candidacy. On the day of the procedure, the donor area is trimmed and local anesthesia is applied. The surgeon then uses a specialized micro-punch tool to extract individual follicular units. These units are carefully preserved and then meticulously implanted into the recipient sites, paying close attention to the angle, direction, and density to ensure a natural-looking result.\n\n**Recovery and Results:**\nPost-procedure, you can expect some mild redness and swelling, which typically subsides within a few days. Most patients can return to non-strenuous activities within a day or two. The transplanted hairs will shed in the first few weeks, which is a normal part of the process. New, permanent hair growth will begin in 3-4 months, with final results visible around 12-18 months.`,
        imageUrl: 'https://picsum.photos/800/600?random=101'
    },
    {
        id: 2,
        title: 'Medical Tourism: Is Traveling for a Hair Transplant Right for You?',
        author: 'Mark Johnson, Patient Coordinator',
        date: '2024-06-28',
        summary: 'Countries like Turkey, Mexico, and Thailand have become hotspots for hair transplants. But is it a good idea? We weigh the pros and cons of medical tourism for hair restoration procedures.',
        content: `The allure of getting a high-quality hair transplant at a fraction of the cost in your home country is strong. Cities like Istanbul and Tijuana have built entire industries around medical tourism, offering all-inclusive packages that cover the procedure, hotel stay, and transportation.\n\n**The Pros:**\n- **Cost Savings:** The most significant advantage. Procedures can be 50-70% cheaper than in the US or UK.\n- **Quality Care:** Many international clinics are JCI-accredited and feature world-class surgeons and technology.\n- **Experience a New Culture:** Combine your procedure with a vacation.\n\n**The Cons & How to Mitigate Them:**\n- **Travel & Logistics:** Traveling after surgery can be uncomfortable. **Mitigation:** Plan to stay in the destination city for at least 5-7 days post-op for initial recovery.\n- **Follow-up Care:** What happens if you have complications once you're home? **Mitigation:** Choose clinics that have clear post-op care protocols and are responsive to international patients. Virtual follow-ups are common.\n- **Research is Crucial:** The quality can vary wildly. **Mitigation:** Do not choose based on price alone. Thoroughly research clinic reviews, surgeon credentials, and look at patient testimonials and before/after photos. Our directory is a great place to start!`,
        imageUrl: 'https://picsum.photos/800/600?random=102'
    }
];

export const PRODUCT_CATEGORIES: ProductCategory[] = [
    { id: 1, name: 'At-Home Devices', description: 'Clinically proven devices for hair regrowth you can use at home.' },
    { id: 2, name: 'Topical Treatments', description: 'Shampoos, serums, and foams to apply directly to the scalp.' },
    { id: 3, name: 'Supplements', description: 'Vitamins and minerals to support hair health from within.' },
    { id: 4, name: 'Post-Op Care', description: 'Essential products for a smooth recovery after a hair transplant.' }
];

export const PRODUCT_REVIEWS: ProductReview[] = [
    { id: 1, name: 'Regrowth MD Laser Cap', categoryId: 1, rating: 4.8, summary: 'An FDA-cleared, clinical-strength laser cap to help regrow hair and reduce thinning. A powerful, non-invasive treatment.', fullReview: 'The Regrowth MD Laser Cap is a standout in the crowded field of at-home hair loss treatments...', affiliateLink: '#', imageUrl: 'https://picsum.photos/800/600?random=301' },
    { id: 2, name: 'Hims Thickening Shampoo', categoryId: 2, rating: 4.5, summary: 'Formulated with saw palmetto to target DHT, a key culprit in hair loss. Great for adding volume and promoting a healthy scalp.', fullReview: 'Hims Thickening Shampoo is a popular choice for those looking to give their hair a fuller appearance...', affiliateLink: '#', imageUrl: 'https://picsum.photos/800/600?random=302' },
    { id: 3, name: 'Nutrafol Hair Growth Supplement', categoryId: 3, rating: 4.7, summary: 'A multi-award-winning supplement that targets the root causes of thinning hair like stress, hormones, and nutrition.', fullReview: 'Nutrafol is a physician-formulated supplement backed by clinical studies...', affiliateLink: '#', imageUrl: 'https://picsum.photos/800/600?random=303' },
    { id: 4, name: 'Post-Op Gentle Healing Foam', categoryId: 4, rating: 4.9, summary: 'A soothing, antiseptic foam designed specifically for the delicate post-transplant scalp. Helps reduce scabbing and itching.', fullReview: 'This is a must-have for anyone in the first 1-2 weeks of recovery...', affiliateLink: '#', imageUrl: 'https://picsum.photos/800/600?random=304' }
];

export const PENDING_CLAIMS: ClaimRequest[] = [
    { id: 1, clinicId: 13, clinicName: 'London Scalp Clinic', submitterName: 'Dr. John Watson', submitterTitle: 'Clinic Director', submitterEmail: 'j.watson@londonscalp.co.uk', verificationMethod: 'email', status: 'pending' },
    { id: 2, clinicId: 11, clinicName: 'Bangkok Beauty Hair', submitterName: 'Priya Sharma', submitterTitle: 'Owner', submitterEmail: 'p.sharma@gmail.com', verificationMethod: 'document', documentProof: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII=', status: 'pending' }
];

export const PENDING_REVIEWS: Review[] = [
    {
        id: 101,
        userId: 'user5',
        clinicId: 16, // SoCal Hair Restoration
        rating: 5,
        comment: 'Absolutely fantastic service from start to finish. The team at SoCal Hair Restoration made me feel comfortable and the results are better than I could have imagined. Highly recommend!',
        date: new Date().toISOString().split('T')[0],
        status: 'pending'
    }
];

export const INITIAL_SUBSCRIBERS: NewsletterSubscriber[] = [
    { id: 1, email: 'early.adopter@email.com', subscribedAt: '2024-01-01' }
];